server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Custom caching rule for static media
    location ~* \.(?:jpg|jpeg|gif|png|ico|svg|css|js|webp)$ {
        root /usr/share/nginx/html;
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
