version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: mehndigo_staging_postgres
    restart: always
    environment:
      POSTGRES_USER: ankit
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mehndigo_staging_db
    volumes:
      - pg_staging_data:/var/lib/postgresql/data
    networks:
      - mehndigo_staging_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mehndigo_staging_backend
    restart: always
    environment:
      NODE_ENV: staging
      PORT: 3000
      DB_HOST: postgres
      DB_USER: ankit
      DB_PASS: 123456
      DB_NAME: mehndigo_staging_db
      JWT_SECRET: staging_super_secret_secret
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - mehndigo_staging_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mehndigo_staging_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - mehndigo_staging_net

volumes:
  pg_staging_data:

networks:
  mehndigo_staging_net:
    driver: bridge
