ALTER TABLE ReferralHistories ADD COLUMN referral_type TEXT NOT NULL DEFAULT 'CUSTOMER_TO_CUSTOMER';
ALTER TABLE ReferralHistories ADD COLUMN referral_code TEXT;
ALTER TABLE ReferralHistories ADD COLUMN qualified_at DATETIME;
ALTER TABLE ReferralHistories ADD COLUMN fraud_flag BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE ReferralHistories ADD COLUMN referral_status TEXT NOT NULL DEFAULT 'REGISTERED';

CREATE TABLE IF NOT EXISTS ReferralRewards (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    reward_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'LOCKED',
    unlocked_at DATETIME,
    redeemed_at DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS referral_rewards_user_type_unique ON ReferralRewards (user_id, reward_type);

INSERT INTO SystemSettings (key, value, created_at, updated_at) 
SELECT 'REFERRAL_C2C_COUNT', '50', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM SystemSettings WHERE key = 'REFERRAL_C2C_COUNT');

INSERT INTO SystemSettings (key, value, created_at, updated_at) 
SELECT 'REFERRAL_C2C_BOOKINGS', '3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM SystemSettings WHERE key = 'REFERRAL_C2C_BOOKINGS');

INSERT INTO SystemSettings (key, value, created_at, updated_at) 
SELECT 'REFERRAL_C2A_COUNT', '10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM SystemSettings WHERE key = 'REFERRAL_C2A_COUNT');

INSERT INTO SystemSettings (key, value, created_at, updated_at) 
SELECT 'REFERRAL_A2A_COUNT', '20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM SystemSettings WHERE key = 'REFERRAL_A2A_COUNT');
