name = "mehndigo-backend"
main = "src/index.js"
compatibility_date = "2024-09-23"

routes = [
  { pattern = "api.mehndigo.in", custom_domain = true }
]

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "mehndigo-super-secret-jwt-token-key-2026"
RAZORPAY_KEY_ID = "rzp_live_TOnEe0jhl1qgO5"
RAZORPAY_KEY_SECRET = "P1O71RSSuCVTAULIlf8WJaru"
EMAIL_USER = "sonudonyadav87@gmail.com"
EMAIL_PASS = "kwemkkniwxyohmvm"
AZURE_EMAIL_FROM = "donotreply@mehndigo.in"
RESEND_API_KEY = ""

[[d1_databases]]
binding = "DB"
database_name = "mehndigo"
database_id = "c25b4a9f-8ad2-4422-85bb-d64ddadcebaa"
